---
title: "Gov 50 Final Project"
author: "Vivien Henz"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to climate change and climate vulnerability. I think I could make an interesting project out of investing who is more likely to suffer from climate change impacts based on certain demographics. If thats not possible, I think i'll lean more into polling on climate and see whether or not a certain factor will make someone vote more towards politicians that include climate change mitigation/adaptation in their campaigns.

```{r}
airquality
climateviews <- read.csv("YCOM6.0_2021_Data_.csv")
```

My research question will be: Does having proggressive viesws on climate change in a city reduce its air pollution levels?

MY hypothesis that is related to the research question is that yes, habitants of a city that have on average more proggressive views will have a city that has reduced air pollution. I'm formulating this hypothesis because of two assumptions: the first one is that people that tend to have more proggressive views on climate change in general choose to live in cities that have a reputation for clean air. why? because proggressives just care more. Secondly, and most importantly, people that tend to have more proggressive views on climate change also tend to vote accordingly. This means that they will vote for candidates that for example will place greater emphasis on measures that reduce CO2 emissions within the city, such as public transport, industrial de-zoning, clean energy alternative projects and so on. The explanatory variable that will be most important to my project will be the average view on climate change of cities, this is measured as the percentage of people that responded postitively to the polling question "Climate Change is Happening.". There are other variables inside the "airquality" database that I imported, such as the opinion on whether to regulate, fund renewable energy or limit CO2 emmissions. For my outcome variabel, PM2.5 concentrations in the cities, the values shown are the highest among the sites in each area. Data from exceptional events are included.  This summary is not adequate in itself to numerically rank CBSAs according to their air quality.  The monitoring data represent the quality of air in the vicinity of the monitoring site and, for some pollutants, may not necessarily represent urban-wide air quality. An observed pattern where greater PM2.5 concentrations are matched with less progressive views on climate change will proove my hypothesis. No pattern observed, or even an opposite pattern will disprove my hypothesis.